---
services: docker
script: script/travis
sudo: required
language: ruby
os: linux
cache:
  bundler: true
  directories:
    - vendor/bundle
branches:
  only:
    - main
env:
  global:
    - DOCKER_EMAIL=contact@jv-conseil.net
    - DOCKER_USERNAME=jvconseil
jobs:
  include:
    - script: true
      stage: precache
    - stage: build
    # --
    # jvconseil/jekyll
    # --
    env: "\
      DOCKER_REPO='\
        jekyll:4.3.3 \
        jekyll:stable \
        jekyll:latest \
        jekyll:pages \
        jekyll:4.0 \
        jekyll:4 \
      '\
    "
    # --
    # jvconseil/jekyll-docker
    # --
    - env: "\
        DOCKER_REPO='\
        jekyll-docker:4.3.3 \
        jekyll-docker:stable \
        jekyll-docker:latest \
        jvconseil:jekyll-docker \
        jekyll-docker:pages \
        jekyll-docker:4.0 \
        jekyll-docker:4 \
        '\
        "
  # --
  # jvconseil/jekyll-minimal
  # --
  - env: "\
      DOCKER_REPO='\
        jekyll-minimal:4.3.3 \
        jekyll-minimal:stable \
        jekyll-minimal:latest \
        jvconseil:jekyll-minimal \
        jekyll-minimal:pages \
        jekyll-minimal:4.0 \
        jekyll-minimal:4 \
      '\
    "
