name: 'Deploy'
on:
  push:
    branches:
      - ruby3.1.4-alpine3.18
  # schedule:
  #   - cron: 2 4 10 * *
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    name: 'Deploy'
    strategy:
      fail-fast: false
      matrix:
        env:
          # -
          #   - jekyll:4.3.2
          #   - jekyll:stable
          #   - jekyll:latest
          #   - jekyll:4.0
          #   - jekyll:4
          -
            - jekyll-docker:4.3.2
            - jekyll-docker:stable
            - jekyll-docker:latest
            - jekyll-docker:4.0
            - jekyll-docker:4
          # -
          #   - minimal:4.3.2
          #   - minimal:stable
          #   - minimal:latest
          #   - minimal:4.0
          #   - minimal:4
          # - jekyll-docker:pages
          # - minimal:pages
          # - jekyll:pages
    steps:
      - uses: actions/checkout@v3

      - name: 'Setup Ruby'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - run: bundle install
      - run: |
          echo $'{\n    "experimental": true\n}' | \
            sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
        name: 'docker experimental'

      # - name: 'docker login'
      #   run: |
      #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
      #       --username ${{ secrets.DOCKER_USERNAME }} \
      #       --password-stdin

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: |
          bundle exec docker-template build $DOCKER_REPO --no-push --force --squash
          bundle exec docker-template push $DOCKER_REPO
        env:
          RUBYOPT: "-W0"
          DOCKER_REPO: "${{join(matrix.env, ' ')}}"
