name: 'Push'
on:
  push:
    branches:
      - ruby3.1.4-alpine3.18
  schedule:
    - cron: 2 4 10 * *
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    name: 'Build'
    strategy:
      fail-fast: false
      matrix:
        env:
          -
            - jekyll/jekyll:4.3.2
            - jekyll/jekyll:stable
            - jekyll/jekyll:latest
            - jekyll/jekyll:4.0
            - jekyll/jekyll:4
          -
            - jekyll/builder:4.3.2
            - jekyll/builder:stable
            - jekyll/builder:latest
            - jekyll/builder:4.0
            - jekyll/builder:4
          -
            - jekyll/minimal:4.3.2
            - jekyll/minimal:stable
            - jekyll/minimal:latest
            - jekyll/minimal:4.0
            - jekyll/minimal:4
          - jekyll/builder:pages
          - jekyll/minimal:pages
          - jekyll/jekyll:pages
    steps:
      - uses: actions/checkout@v3

      - name: 'Setup Ruby'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - run: bundle install
      - run: |
          echo $'{\n    "experimental": true\n}' | \
            sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
        name: 'docker experimental'

      # - name: 'docker login'
      #   run: |
      #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
      #       --username ${{ secrets.DOCKER_USERNAME }} \
      #       --password-stdin

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: |
          bundle exec docker-template build "$DOCKER_REPO" --no-push --force --squash
          bundle exec docker-template push "$DOCKER_REPO"
        env:
          RUBYOPT: "-W0"
          DOCKER_REPO: "${{join(matrix.env, ' ')}}"
